language: sourcepawn
sudo: false

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp

before_script:
    # install smbuilder
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local
    - cd ..

    # install the sourcemod compiler
    - wget "http://sourcemod.net/latest.php?os=linux&version=1.10" -O sourcemod.tar.gz
    - tar xfz sourcemod.tar.gz
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"

    - cd ../../..

script:
    - smbuilder --flags="-E"
