language: sourcepawn
sudo: false

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp

env:
    - SMV=1.10

before_script:
    # install smbuilder
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local
    - cd ..

    # install the sourcemod compiler
    - SMP="https://sourcemod.net/latest.php?version=${SMV}&os=linux"
    - wget $SMP
    - tar xfz $(basename $SMP)
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"

    - cd ../../..

script:
    - smbuilder --flags="-E"
