name: MyStore Version

on:
  push:
    branches: mystore

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download sourcemod
      run: |
        wget "http://www.sourcemod.net/latest.php?version=1.10&os=linux" -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp
    - name: Remove unnessesary files
      run: rm addons/sourcemod/scripting/*.sp
    - name: Move required include files into the workspace
      run: mv scripting/include/* addons/sourcemod/scripting/include
    - name: Move plugin into workspace
      run: mv scripting/*.sp addons/sourcemod/scripting
    - name: Compiling Shavit-Credits
      run: |
        for file in addons/sourcemod/scripting/*.sp
        do
          echo -e "\nCompiling $file..." 
          addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 $file
        done
