on:
  push:
    branches:
      - store
    
jobs:
  Build:
    name: Sourcemod Store Version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.11.x"

    - name: Compiling shavit-credits.sp
      run: |
        which spcomp
        echo $includePath
        ls -l $scriptingPath
        cat $(which spcomp)
        spcomp -iscripting/include scripting/shavit-credits.sp